### ISSUE TITLE
I have a question about "from confomer.encoder import ConformerBlock"

### ISSUE THREAD

**Issue by MayWang1007** [lightning830/E2E_AudioVisualSpeechRecognition#2]
Thanks for sharing your work.
Here is my question,I use "pip install conformer" to install the conformer module ,but failed to import ConformerBlock and ConformerEncoder.**Could you please tell me which module and the version you use?**

**Comment by lightning830** [comment]
Hello. 
I use "https://github.com/sooftware/conformer". Please install this one to try it out.
Thank you.
